import "../App.css";

export default function NextSteps() {
  return (
    <>
      <div className="parallax-layer">
        <img
          className="parallax-layer-i"
          src="imgs/bookshelf-home-2.jpg"
          alt="Bookshelf"
        />
      </div>
      <h1 className="report-header">Next Steps</h1>
        <h2 className="report-header">Prioritization and Impact</h2>
          <p className="report-para">The next steps to this project should focus on improving both model performance and accuracy rating. A top priority is expanding and diversifying the training dataset to include additional categories/genres, targetting data with less multi-genre categorizations, and for recommendation system usage, include meaningful user feedback per book to retrain this model. This would help reduce classification ambiguity in overlapping categories like as seen in Science, History, and Art, and improve the model's ability to generalize across different writing styles and formats. Incorporating user feedback from the interface, such as manual corrections to predicted tags, could also enable a feedback loop for future model improvement.</p>
          <p className="report-para">From a system impact perspective, future development should also prioritize deployment and scalability. This includes packaging the trained roBERTa model as a artifact with a version for currating reasons and continuing to integrate automated monitoring for prediction quality and time latency. Additionally this project could be optimize via more experimentation and cutting edge resources being made available. Even the model suggested came from more research and study on newer and more improved systems related closely to this capstone. I could also attempt to reduce inference cost while maintaining accuracy. Together, these next steps aim to transform this capstone into a full-scale system capable of supporting automated book tagging with heavy traffic and with meaningful benefits for libraries, publishers, and content discovery platforms. And with recommendation systems becoming a focal point in the industry, this categorization system along with additional research and user input has the makings to produce something meaningful in the industry.</p>

        <h2 className="report-header">Experimentation Strategy</h2>
          <p className="report-para">Future experimentation will focus on improving classification performance and robustness through controlled model and data experiments. Many of the trial and errors spent time that under more seasoned eyes could be reduced to a fraction when experimenting with models which prevented further experimentation for the duration of this capstone. One immediate direction is to evaluate alternative transformer architectures, such as I had done with DistilBERT for faster inference, and perhaps look into other models such as DeBERTa for potentially higher accuracy. I could rerun the experimental phase using the same training and evaluation pipeline to ensure all models have a fair comparison. This would also include hyperparameter optimization where I could test the batch sizes, learning rates, and number of epochs. By doing so the hyperparameters can be explored using grid or Bayesian search methods to identify configurations that might best improve F1-score and minimize overfitting in the model.</p>
          <p className="report-para">Additional experiments would help investigate the impact of different inputs and data strategies. This includes comparing models trained on descriptions alone versus models that incorporate other book metadata beyond the descriptions, author and title which had been tested in my current capstone model. Data augmentation techniques such as paraphrasing, synonym replacement, or back-translation may also assist in improvement to the performance on underperforming or semantically overlapping genres as it would provide a variety of descriptions per book to categorize with. All experiments should be tracked using consistent metrics as done in this capstone (accuracy, weighted F1, and confusion matrices) and replicated to ensure a reliable performance comparison for the models.</p>

        <h2 className="report-header">Error Analysis & Feedback Loop</h2>
          <p className="report-para">Future work will include a more systematic error analysis to better understand model limitations and guide targeted improvements. Misclassified examples identified through confusion matrices and classification reports will be manually reviewed to determine whether errors developed from ambiguous category definitions, overlapping vocabulary, or lack of distinct data/metadata. Particular attention will be given to categories often confused in the model, such as Science versus Fantasy/Science Fiction and Art versus History, to identify patterns that can inform data curation, label refinement, or model architecture choices. In the end, it is important to create a feedback loop mechanism for human intervention to assist in the retraining of the model when a new version is deployed.</p>
          <p className="report-para">A feedback loop is good for incorporating continuous learning and performance monitoring after the capstone's final review. Currently the beginnings of a feedback loop have been created. There is a feature built into the UI in order to update the category field based on what the user believes. This can later be extended into a new table to collect multiple responses that could be averaged in the dataset and used to retrain the model in the future. This idea would need to be more thoroughly flushed out as time allows to be more meaningful than the simple feedback loop currently inside the program. However, already the beginnings of a feedback loop have been considered in order to pursue the correct direction for further implementation beyond the capstone's final date.</p>
        
        <h2 className="report-header">Resource & Timeline Planning</h2>
          <p className="report-para">The next phases of development beyond the course's end should consider of available resources, time, and future implementation. Due to the costs associated with this project, future planning should include researching into various online cloud platforms to look at the costs for long term solution. Already much of the cost associated to the project has been cut as much as it could considering what has been studied, but more time and effort will be needed in order to revise versions, rebuild, and retrain the model to continuously work with future implementations of feedback loops, updated hyperparameters and model changes, as well as any monitoring that will be needed for long term app usage of this project.</p>
    </>
  );
}
